import React, { useEffect, useState } from 'react';
import { io, Socket } from 'socket.io-client';

export default function App() {
  const [token, setToken] = useState(localStorage.getItem('proctorToken') || '');
  const [socket, setSocket] = useState<Socket | null>(null);
  const [frames, setFrames] = useState<Record<string, string>>({});
  const [flags, setFlags] = useState<any[]>([]);

  // We mock a target session ID for demonstration of joining a room
  const targetSessionId = "mock-session-123";

  useEffect(() => {
    if (!token) return;

    // Connect to the secure /proctor namespace on the backend
    const BACKEND_URL = import.meta.env.VITE_API_URL || 'http://localhost:4000';
    const newSocket = io(`${BACKEND_URL}/proctor`, {
      auth: { token }
    });

    newSocket.on('connect', () => {
      console.log('Connected to Proctor Namespace');
      // Proctor explicitly requests to monitor a session room
      newSocket.emit('proctor:monitor', { sessionId: targetSessionId });
    });

    // Receive live frame from the backend WebSocket
    newSocket.on('live-frame', (data: { studentId: string; frameData: string; timestamp: number }) => {
      setFrames(prev => ({ ...prev, [data.studentId]: data.frameData }));
    });

    // Receive AI-driven Proctoring Flags generated by the Phase 8 AI Engine
    newSocket.on('proctoring-alert', (flag: any) => {
      setFlags(prev => [flag, ...prev]);
    });

    setSocket(newSocket);
    return () => { newSocket.disconnect(); };
  }, [token]);

  if (!token) {
    return (
      <div style={{ padding: '40px', fontFamily: 'sans-serif', maxWidth: 400, margin: '0 auto' }}>
        <h2>Proctor Login</h2>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
          <input 
            type="text" 
            placeholder="Paste your JWT Token" 
            onChange={e => setToken(e.target.value)}
            style={{ padding: 10, fontSize: 16 }}
          />
          <button 
            onClick={() => localStorage.setItem('proctorToken', token)}
            style={{ padding: 10, background: '#2563eb', color: 'white', border: 'none', cursor: 'pointer' }}
          >
            Connect Dashboard
          </button>
        </div>
      </div>
    );
  }

  return (
    <div style={{ padding: 20, fontFamily: 'sans-serif' }}>
      <h2>Real-Time Proctor Dashboard</h2>
      
      <div style={{ display: 'flex', gap: '20px' }}>
        {/* Live Monitoring Panel */}
        <div style={{ flex: 2 }}>
          <h3>Live Feeds</h3>
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: '15px' }}>
            {Object.keys(frames).length === 0 && (
              <p style={{ color: '#666' }}>Waiting for student webcam frames...</p>
            )}
            
            {Object.entries(frames).map(([studentId, frameB64]) => (
              <div key={studentId} style={{ border: '1px solid #ccc', borderRadius: 8, overflow: 'hidden', background: '#fff' }}>
                <div style={{ padding: '8px 12px', background: '#f8fafc', borderBottom: '1px solid #eee', fontWeight: 'bold' }}>
                  Student: {studentId}
                </div>
                <img 
                  src={frameB64} 
                  alt={`Live feed from ${studentId}`} 
                  width={320} 
                  height={240} 
                  style={{ display: 'block', background: '#000', objectFit: 'contain' }} 
                />
              </div>
            ))}
          </div>
        </div>

        {/* AI Alerts Sidebar */}
        <div style={{ flex: 1, borderLeft: '1px solid #e5e7eb', paddingLeft: 20 }}>
          <h3>AI Flags Engine</h3>
          <ul style={{ listStyle: 'none', padding: 0, margin: 0, display: 'flex', flexDirection: 'column', gap: 10 }}>
            {flags.length === 0 && (
              <li style={{ color: '#666' }}>No suspicious activity detected.</li>
            )}
            
            {flags.map((flag, i) => (
              <li key={i} style={{ padding: 15, background: flag.severity === 'HIGH' ? '#fef2f2' : '#fffbeb', border: `1px solid ${flag.severity === 'HIGH' ? '#fca5a5' : '#fde68a'}`, borderRadius: 6 }}>
                <div style={{ fontWeight: 'bold', color: flag.severity === 'HIGH' ? '#dc2626' : '#d97706' }}>
                  {flag.severity} RISK: {flag.eventType}
                </div>
                <div style={{ fontSize: '0.85em', marginTop: 5, color: '#4b5563' }}>
                  Session: {flag.sessionId}
                </div>
              </li>
            ))}
          </ul>
        </div>
      </div>
    </div>
  );
}
