import IORedis from 'ioredis';
import { Server } from 'socket.io';

/**
 * Listens to the Redis PubSub channel for AI Flags generated by the Phase 8 Proctoring Worker,
 * and bridges them back to the connected Socket.IO Proctors in real-time.
 */
export const startAlertReceiver = (io: Server) => {
  const subscriber = new IORedis(process.env.REDIS_URL || 'redis://localhost:6379');
  
  subscriber.subscribe('proctoring-alerts');
  
  subscriber.on('message', (channel, message) => {
    if (channel === 'proctoring-alerts') {
      try {
        const alert = JSON.parse(message);
        
        // Broadcast specifically to proctors actively monitoring the student's session room
        io.of('/proctor').to(`session:${alert.sessionId}`).emit('proctoring-alert', alert);
        
        // Also broadcast to global admins
        io.of('/admin').to('system:alerts').emit('global-alert', alert);
      } catch (e) {
        console.error('Failed to parse proctoring alert message', e);
      }
    }
  });
};
